name: restaurant_app
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #state
  provider: ^6.0.3

  #Context
  kartal: ^2.3.2

  #Animation
  lottie: ^1.4.2

  #Google
  google_fonts: ^3.0.1
  image_picker: ^0.8.5
  flutter_svg: ^1.1.1+1
  contained_tab_bar_view: ^0.8.0

  #Firebase
  firebase_core: ^1.14.1
  firebase_auth: ^3.3.14
  cloud_firestore: ^3.1.12
  firebase_storage: ^10.2.12

  #Core
  uuid: ^3.0.6
  fluttertoast: ^8.0.9
  page_transition: ^2.0.9
  intl: ^0.17.0

  #DateTime
  datetime_picker_formfield: ^2.0.0
  carousel_slider: ^4.1.1
  flutter_datetime_picker: ^1.5.1
  linear_step_indicator: ^1.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/svgs/
    - assets/icons/bottom_navbar/
    - assets/lotties/
